# -*- coding: utf-8 -*-
"""sns1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GlALjgPufVwVOPpChsZRagTQDZkL3Hja
"""

# Install
!pip install opencv-python

import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files, output
from google.colab.patches import cv2_imshow
from IPython.display import Javascript, display, HTML
from base64 import b64decode, b64encode

# Load face detector
face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades + "haarcascade_frontalface_default.xml"
)

# ---------------- CAMERA FUNCTION ----------------
def take_photo(filename='photo.jpg', quality=0.8):
    js = Javascript('''
        async function takePhoto(quality) {
          const div = document.createElement('div');
          const button = document.createElement('button');
          button.textContent = '📸 Capture';
          div.appendChild(button);

          const video = document.createElement('video');
          const stream = await navigator.mediaDevices.getUserMedia({video: true});

          document.body.appendChild(div);
          div.appendChild(video);
          video.srcObject = stream;
          await video.play();

          await new Promise((resolve) => button.onclick = resolve);

          const canvas = document.createElement('canvas');
          canvas.width = video.videoWidth;
          canvas.height = video.videoHeight;
          canvas.getContext('2d').drawImage(video, 0, 0);

          stream.getTracks().forEach(track => track.stop());
          div.remove();

          return canvas.toDataURL('image/jpeg', quality);
        }
    ''')
    display(js)
    data = output.eval_js('takePhoto({})'.format(quality))
    binary = b64decode(data.split(',')[1])

    with open(filename, 'wb') as f:
        f.write(binary)

    return filename

# ---------------- MENU ----------------
print("Choose Option:")
print("1 - Live Camera")
print("2 - Upload Image")
print("3 - Upload Video")

choice = input("Enter choice: ")

# ---------------- CAMERA ----------------
if choice == "1":
    path = take_photo()
    img = cv2.imread(path)

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.equalizeHist(gray)

    faces = face_cascade.detectMultiScale(
        gray, scaleFactor=1.1, minNeighbors=3, minSize=(30,30)
    )

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)

    cv2_imshow(img)

    if len(faces) >= 1:
        print("✅ RESULT: HUMAN DETECTED (REAL)")
    else:
        print("⚠️ RESULT: NO HUMAN (AI / FAKE)")

# ---------------- IMAGE ----------------
elif choice == "2":
    uploaded = files.upload()
    file_name = list(uploaded.keys())[0]

    img = cv2.imread(file_name)

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    gray = cv2.equalizeHist(gray)

    faces = face_cascade.detectMultiScale(
        gray, scaleFactor=1.1, minNeighbors=3, minSize=(30,30)
    )

    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)

    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.show()

    if len(faces) >= 1:
        print("✅ RESULT: HUMAN IMAGE (REAL)")
    else:
        print("⚠️ RESULT: AI / FAKE IMAGE")

# ---------------- VIDEO ----------------
elif choice == "3":
    uploaded = files.upload()
    file_name = list(uploaded.keys())[0]

    # Play video
    mp4 = open(file_name,'rb').read()
    data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

    display(HTML(f"""
    <video width=400 controls>
          <source src="{data_url}" type="video/mp4">
    </video>
    """))

    cap = cv2.VideoCapture(file_name)

    frame_count = 0
    human_frames = 0
    check_frames = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame_count += 1

        # 🔥 Check only every 10th frame
        if frame_count % 10 != 0:
            continue

        check_frames += 1

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        gray = cv2.equalizeHist(gray)

        faces = face_cascade.detectMultiScale(
            gray, scaleFactor=1.1, minNeighbors=3, minSize=(30,30)
        )

        if len(faces) >= 1:
            human_frames += 1

        if check_frames % 5 == 0:
            plt.imshow(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
            plt.axis("off")
            plt.show()

    cap.release()

    print("Checked Frames:", check_frames)
    print("Human Frames:", human_frames)

    # 🔥 FINAL DECISION
    if human_frames >= 3:
        print("✅ RESULT: HUMAN VIDEO (REAL)")
    else:
        print("⚠️ RESULT: AI / FAKE VIDEO")

else:
    print("Invalid choice")